#!/bin/bash

for FILE in P*[0-9].JPG
do
	TIME=`exif -t 0x0132 --ifd=0 $FILE | grep Value| awk '{print $NF}'`
	DATE="2016:02:07 $TIME"
	echo $FILE $DATE
	NEW=$FILE.new
	exif -t 0x0132 --ifd=0 --set-value="$DATE" -o $NEW $FILE
	exif -t 0x9003 --ifd=EXIF --set-value="$DATE" -o $NEW.1 $NEW
	exif -t 0x9004 --ifd=EXIF --set-value="$DATE" -o $NEW.2 $NEW.1

done


